language: php
sudo: false

php: 7.0

env:
  global:
    - DRUPAL_CORE=8.4.x
  matrix:
    - MODE=cs
    - MODE=functional

mysql:
  database: message_ui
  username: root
  encoding: utf8

before_script:

  # Remove Xdebug as we don't need it and it causes "PHP Fatal error: Maximum
  # function nesting level of '256' reached."
  # We also don't care if that file exists or not on PHP 7.
  - phpenv config-rm xdebug.ini || true

  # Remember the current directory for later use in the Drupal installation.
  - TESTDIR=$(pwd)

  # Navigate out of module directory to prevent blown stack by recursive module
  # lookup.
  - cd ..

  # Create database.
  - mysql -e 'create database message_ui'

  # Export database variable for kernel tests.
  - export SIMPLETEST_DB=mysql://root:@127.0.0.1/message_ui


script:
  - if [[ $MODE == cs ]]; then
    bash scripts/travis/cs.sh;
    fi
  - if [[ $MODE == functional ]]; then
    bash scripts/travis/functional.sh;
    fi
